<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="che" failures="1" tests="4" name="AdminSettings" time="67.858" errors="0" timestamp="2024-09-03T00:06:53 IST">
  <testcase classname="testCases.TC01_LoginToBasePage" name="login" time="0.003"/>
  <testcase classname="testCases.TC02_AddTeamMember" name="addTeamMember" time="12.753"/>
  <testcase classname="testCases.TC03_verifyNameOnAddingOfDuplicateEmail" name="test2" time="14.525">
    <failure type="java.lang.AssertionError" message="expected [che3] but found [che32024.09.03.00.06.39]">
      <![CDATA[java.lang.AssertionError: expected [che3] but found [che32024.09.03.00.06.39]
at testCases.TC03_verifyNameOnAddingOfDuplicateEmail.test2(TC03_verifyNameOnAddingOfDuplicateEmail.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="testCases.TC04_dummyTestCase" name="login" time="0.004"/>
</testsuite> <!-- AdminSettings -->
